---
title: "check_couple"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{check_couple}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.width = 8,
  fig.height = 6
)
```

```{r setup, message = FALSE}
library(tidyverse)
library(halfplus7)
```

```{r}
age1_list <- c(18:100)
age2_list <- c(18:100)

combinations <- expand.grid(age1 = age1_list, age2 = age2_list)

couple_df <- combinations %>%
  mutate(verdict_long = check_couple(age1, age2),
         verdict = case_when(
    str_detect(verdict_long, "NOT") ~ "No",
    !str_detect(verdict_long, "NOT") ~ "Yes"
  ))

ggplot(couple_df, aes(x = age1, y = age2, color = verdict)) +
  geom_point(alpha = 0.5) +
  scale_color_manual(values = c("Yes" = "darkgreen", "No" = "red")) +
  labs(
    title = "'Half-Your-Age-Plus-Seven' Ruling on Different Age Combinations",
    x = "Age of First Person",
    y = "Age of Second Person",
    color = "Age Appropriate Match?"
  ) +
  theme_minimal()


```


